version: '3'

services:
  postgres-database:
    image: 'postgres:15.1-alpine'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432    

  fluent-bit:
    image: fluent/fluent-bit
    ports:
      - 24224:24224/tcp
      - 24224:24224/udp
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./docker/volume:/tmp

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
      
  grafana:
    image: grafana/grafana:latest
    user: 1000:1000
    ports:
      - 3000:3000
    volumes:
      - "./docker/volumes/grafana:/var/lib/grafana:rw"
