version: '3'

services:
  postgres-database:
    image: 'postgres:15.1-alpine'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432    
