// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"monolith/adapter/output/database"
	"monolith/application"
	"monolith/domain/usecase"
	"monolith/infrastructure/http/router"
)

// Injectors from wire.go:

func InitializeRouters() (*gin.Engine, error) {
	createUser := database.NewCreateUserPostgresRepository()
	usecaseCreateUser, err := usecase.NewCreateUserUseCase(createUser)
	if err != nil {
		return nil, err
	}
	createUserApplication, err := application.NewCreateUserApplication(usecaseCreateUser)
	if err != nil {
		return nil, err
	}
	getUser := database.NewGetUserPostgresRepository()
	usecaseGetUser, err := usecase.NewGetUserUseCase(getUser)
	if err != nil {
		return nil, err
	}
	getUserApplication, err := application.NewGetUserApplication(usecaseGetUser)
	if err != nil {
		return nil, err
	}
	engine, err := router.NewRouter(createUserApplication, getUserApplication)
	if err != nil {
		return nil, err
	}
	return engine, nil
}

// wire.go:

var RepositoriesSet = wire.NewSet(database.NewCreateUserPostgresRepository, database.NewGetUserPostgresRepository)

var UseCasesSet = wire.NewSet(usecase.NewCreateUserUseCase, usecase.NewGetUserUseCase)

var ApplicationsSet = wire.NewSet(application.NewCreateUserApplication, application.NewGetUserApplication)

var RoutersSet = wire.NewSet(router.NewRouter)

var AppSet = wire.NewSet(RepositoriesSet, UseCasesSet, ApplicationsSet, RoutersSet)
