database:
  user: postgres
  password: 123456
  net: tcp
  addr: 127.0.0.1:5432
  dbname: ortisan-broker
opentelemetry:
  agent_host: localhost
  agent_port: 6831
server:
  address: 8080
  name: user-service